---
- name: Ensure cUrl is installed.
  win_chocolatey:
     name: curl
     state: present

- name: Ensure Java RE is installed
  win_chocolatey:
     name: jre8
     state: present

- name: Ensure Tomcat is installed.
  win_chocolatey:
     name: tomcat
     state: present

- name: Set the insecure tomcat-users.xml file in the right place
  template:
    src: tomcat-users.xml
    dest: "C:\\ProgramData\\Tomcat9\\conf\\tomcat-users.xml"
  register: tomcat_users

- name: Allow access to manager gui from anywhere
  template:
    src: context.xml
    dest: "C:\\ProgramData\\Tomcat9\\webapps\\manager\\META-INF\\context.xml"
  register: tomcat_context
     
- name: Configure service to run as system
  win_service:
    name: Tomcat9
    start_mode: auto
    username: LocalSystem
    password: ""
    state: restarted
    
- include: firewall_8080.yml

