---
- name: Ensure cUrl is installed.
  win_chocolatey:
     name: curl
     state: present

- name: Ensure Java RE is installed
  win_chocolatey:
     name: jre8
     state: present

- name: Ensure Tomcat is installed.
  win_chocolatey:
     name: tomcat
     state: present
     
- name: Configure service to run as system
  win_service:
    name: Tomcat9
    start_mode: auto
    username: LocalSystem
    password: ""
    state: restarted
    
- include: firewall_8080.yml
